name: randomness-mongodb
services:
  mongodb:
    image: mongo:latest
    command: mongod --config /etc/mongo/mongod.conf
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - mongodb_data:/data/db
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=0
    env_file:
      - ../.env

volumes:
  mongodb_data:
    driver: local
