name: randomness-mongodb
services:
  mongodb:
    image: mongo:latest
    command: mongod --config /etc/mongo/mongod.conf
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - mongodb_data:/data/db
    environment:
      GLIBC_TUNABLES: "glibc.pthread.rseq=1"
    env_file:
      - ../.env
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

volumes:
  mongodb_data:
    driver: local
